version: '3'

services:
  db:
    image: postgres:13.7-alpine
    privileged: true
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data