version: '3'

services:
  db:
    image: postgres:13.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data

  backend:
    build:
      context: ./store
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && gunicorn store.wsgi -b 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: store.settings.debug_ext

