# Generated by Django 4.0 on 2022-06-19 22:12

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('storeapp', '0003_category_site_product_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
